export const CATEGORIES = [
  "accessory",
  "clothing",
  "bags & wallet",
  "documents",
  "electronics",
  "food & beverages",
  "miscellaneous",
  "furniture",
  "toys & games",
  "health & beauty",
  "home appliances",
  "sports & outdoors",
  "automotive",
  "books & stationery",
  "jewelry",
  "art & collectibles",
  "tools & equipment",
  "garden supplies",
] as const;
// export const TypeCategory = CATEGORIES
